apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr                                     # This is the recommended name, but you can change it
  namespace: CPD_INSTANCE_NAMESPACE                             # Replace with the project where you will install Cloud Pak for Data
spec:
  license:
    accept: true
    license: CPD_LICENSE                      # Specify the Cloud Pak for Data license you purchased
  storageClass: STORAGE_CLASS                     # Replace with the name of a RWX storage class
  zenCoreMetadbStorageClass: ZEN_CORE_METADB_STORAGE_CLASS        # (Recommended) Replace with the name of a RWO storage class
  version: "4.0.1"